# Generated by Django 4.2.13 on 2024-07-08 06:49

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Sushi',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=32)),
                ('price', models.PositiveIntegerField()),
                ('description', models.TextField(max_length=999)),
                ('slug', models.SlugField(max_length=64)),
                ('type', models.CharField(max_length=3)),
                ('image', models.ImageField(upload_to='media/sushi/')),
                ('rate', models.SmallIntegerField(max_length=1)),
            ],
            options={
                'verbose_name': 'Суши',
                'verbose_name_plural': 'Суши',
                'db_table': 'sushi',
            },
        ),
    ]
