# Generated by Django 4.2.13 on 2024-07-08 20:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_alter_sushi_rate'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sushi',
            name='image',
            field=models.ImageField(upload_to='sushi/'),
        ),
    ]
